# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8686
  servlet:
    context-path: /
spring: 
  datasource:
     druid: 
      systemDB: 
        name: systemDB
        url: jdbc:mysql://localhost:3306/baseplatform_db?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
      businessDB: 
        name: businessDB
        url: jdbc:mysql://localhost:3306/obeyplatform_db?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456